name: Extract Zip Directly
on:
  push:
    branches: [ main ] 

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write # دادن دسترسی برای پوش کردن تغییرات
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip File
        run: |
          # گذاشتن اسم فایل داخل کوتیشن برای حل مشکل پرانتز و فاصله
          unzip -o "zenfocus-clock-screensaver (1).zip" -d . 
          rm -f "zenfocus-clock-screensaver (1).zip"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-extracted zip file via GitHub Actions"
          git push origin main
